# Pandas Introduction

## Objective

Learn the basics of Pandas.

In [11]:
import pandas as pd

In [12]:
data = [10,20,30,40]

series = pd.Series(data)

series

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
type(series)

pandas.Series

In [14]:
student = {
    "Name":["Bhushan","Rahul","Amit"],
    "Age":[22,23,21]
}

df = pd.DataFrame(student)

df

      Name  Age
0  Bhushan   22
1    Rahul   23
2     Amit   21

In [15]:
type(df)

pandas.DataFrame

In [16]:
print(df.shape)

(3, 2)

In [17]:
print(df.columns)

Index(['Name', 'Age'], dtype='str')

In [18]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [20]:
df.describe()

        Age
count   3.0
mean   22.0
std     1.0
min    21.0
25%    21.5
50%    22.0
75%    22.5
max    23.0