In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(r"D:\ml-roadmap\datasets\raw\titanic.csv")

In [10]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
df.groupby("Pclass")["Age"].mean()

Pclass
1    40.918367
2    28.777500
3    24.027945
Name: Age, dtype: float64

In [13]:
df.groupby("Pclass").size()

Pclass
1    107
2     93
3    218
dtype: int64

In [17]:
df.groupby("Sex")["Age"].size()

Sex
female    152
male      266
Name: Age, dtype: int64

In [18]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    94.280297
2    22.202104
3    12.459678
Name: Fare, dtype: float64

In [19]:
df.groupby("Pclass")["Fare"].agg(["mean","max","min"])

             mean       max     min
Pclass
1       94.280297  512.3292  0.0000
2       22.202104   73.5000  9.6875
3       12.459678   69.5500  3.1708

In [20]:
df.groupby("Sex")[["Age","Fare"]].mean()

              Age       Fare
Sex
female  30.272362  49.747699
male    30.272732  27.527877